#!/bin/bash
# backups all the enabled services from multi-user target

TARGETS="multi-user.target.wants"

dump () {
    for target in $TARGETS; do
        find /etc/systemd/system/$target -type l -name *.service -exec basename {} \;
    done
}

restore () {
    if [[ "$(id -u)" == "0" ]]; then
        SUDO=sudo
    else
        SUDO=""
    fi
    while read service; do
        $SUDO systemctl enable $service
    done < $1
}

case $1 in
    ""|dump)
        dump
        ;;
    restore)
        if [[ -z $2 ]]; then
            echo "No backup file specified"
            exit 1
        fi
        restore $2
        ;;
    *)
        echo "Invalid action"
        ;;
esac

# vim: ft=sh
